routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


//public mpesa webhooks
Route::post('/webhook', 'PaymentController@webhook');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    //only logged in users allowed below
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    //only logged inn user allowed above

    Route::get('/', 'HomeController@index');

    Route::resource('users', 'UsersController');
    Route::resource('store', 'StoreController');
    Route::resource('customers', 'CustomersController');
    Route::resource('itemcategories', 'StoreCategoryController');
    Route::resource('itemtype', 'ItemtypeController');
    Route::resource('items', 'ItemsController');
    Route::resource('drivers', 'DriversController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('delivery_services', 'DeliveryServiceController');
    Route::resource('orders', 'OrdersController');
    Route::resource('loyalty_rewords', 'LoyaltyrewordsController');
    Route::resource('corporate_subscriptions', 'CorporatesubscriptionsController');

    Route::prefix('dashboard')->group(function () {
        Route::get('/sms-groups', 'BulksendController@index');
        Route::post('/send-text', 'BulksendController@sendMessage');
        Route::get('/single-sms', 'BulksendController@singleUser');


    });

    //cooporate groups
    Route::prefix('corporate_subscription')->group(function () {
        Route::resource('groups', 'CorporatesubscriptiongroupsController');
        Route::post('temp/users', 'CorporatesubscriptiongroupsController@importusers');
        Route::resource('meals', 'CorporatesubscriptionsmealsController');
        Route::resource('subscribers', 'CorporatesubscriptionusersController');
        Route::resource('grubsubsorders', 'CorporateordersController');
        Route::resource('payments', 'CorporatepaymentController');

    });


    //Mpesa transactions
     Route::prefix('mpesa')->group(function () {
        Route::resource('payments', 'MpesaPaymentsController');
    });


    ///livewire routes
    //Route::view('allstores','store.index');


});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/CorporatesubscriptionusersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Corporateusers;
use App\Corporatesubscriptiongroups;
use App\Customer;

class CorporatesubscriptionusersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subscribers = Corporateusers::with('group:reference_code,subscription_group_name','customer:iUserId,vName,vEmail,vLastName,vPhone')->get()->toArray();
       // return $subscribers;
        return view('corporatesubscriptionusers.index', compact('subscribers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/corporatesubscriptionusers/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h5>Add Subscriptions</h5>
        </div>
    </div>
      <div class="row">
        <div class="col-6">
            @if(Session::has('message'))
                <p class="alert alert-success">{{ Session::get('message') }}</p>
            @endif
            <div class="clearfix"></div>
         <form action="{{ route('corporate_subscriptions.store') }}" method="POST" enctype="multipart/form-data">
             @csrf
                <div class="form-group">
                 <input type="text"  class="form-control" value="{{ old('subscription_name') }}" name='subscription_name' class="form-control" id="" placeholder="Subscription Name" required>
                </div>
                <div class="form-group">
                     <input type="email" value="{{ old('email') }}"  name='email' class="form-control" id="" placeholder="Email" required>
                </div>
                <div class="form-group">
                     <input type="text" value="{{ old('phoneNumber') }}"  name='phoneNumber' class="form-control" id="" placeholder="Phonenumber" required>
                </div>
                <div class="form-group">
                
                    <div class="custom-file">
                        <input type="file" name="subscription_image" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Subscription Image</label>
                    </div>
                </div>
                <div class="form-group">
                     <input type="text" value="{{ old('subscription_location') }}"  name='subscription_location' class="form-control" id="" placeholder="subscription_location" required>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
           </form>
        </div>
       </div>
    </div>


@endsection

resources/views/corporatesubscriptionusers/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h4>Corporate Orders</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="table-responsive text-nowrap">
                <table class="table table-fixed table-hover">
                    <thead>
                        <tr>
                            <th  scope="col">ID</th>
                            <th  scope="col">Group Name </th>
                            <th  scope="col">Name</th>
                            <th  scope="col">Email</th>
                            <th  scope="col">Phonenumber</th>
                            <th  scope="col">Joined Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php ($i = 0)
                          @foreach ($subscribers as $user)
                            <tr>
                                <td>{{ ++$i }}</td>
                                @foreach( $user['group'] as $oderby)
                                  <td> {{  $oderby['subscription_group_name'] }} </td>
                                @endforeach
                                @foreach( $user['customer'] as $oderby)
                                  <td> {{  $oderby['vName'] }}  {{  $oderby['vLastName'] }} </td>
                                @endforeach
                                @foreach( $user['customer'] as $oderby)
                                  <td> {{  $oderby['vEmail'] }} </td></td>
                                @endforeach
                                 @foreach( $user['customer'] as $oderby)
                                  <td>{{ $oderby['vPhone'] }}</td>
                                @endforeach
                                <td>{{ $user['created_at'] }}</td>
                            </tr>
                            @endforeach
                            
                    </tbody>
                </table>
             </div>
           </div>
      </div>
</div>
@endsection

resources/views/corporatesubscriptionusers/show.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h4>Cooporate Groups</h4>
        </div>
        <div class="col-6 text-right">
            <a href="{{ route('groups.create') }}" class="btn btn-primary">Add Group</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Group Name</th>
                            <th>Contact Person</th>
                            <th>Phonenumber</th>
                            <th>Total Members</th>
                            <th>Created at</th>
                            <th>View Members </th>
                        </tr>
                    </thead>
                    <tbody>
                        @php ($i = 0)
                          @foreach ($groups as $group)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td><a href="{{  route('groups.show', $group['id']) }}">{{ $group['name'] }}</a></td>
                                <td>{{ $group['contact_person'] }}</td>
                                <td>{{ $group['phoneNumber'] }}</td>
                                <td>{{ $group['membersNo'] }}</td>
                                <td>{{ $group['created_at'] }}</td>
                                <td><a href="{{  route('groups.show', $group['id']) }}">View Members</a></td>

                            </tr>
                            @endforeach
                            
                    </tbody>
                </table>
           </div>
      </div>
</div>
@endsection