routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


//public mpesa webhooks
Route::post('/webhook', 'PaymentController@webhook');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    //only logged in users allowed below
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    //only logged inn user allowed above

    Route::get('/', 'HomeController@index');

    Route::resource('users', 'UsersController');
    Route::resource('store', 'StoreController');
    Route::resource('customers', 'CustomersController');
    Route::resource('itemcategories', 'StoreCategoryController');
    Route::resource('itemtype', 'ItemtypeController');
    Route::resource('items', 'ItemsController');
    Route::resource('drivers', 'DriversController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('delivery_services', 'DeliveryServiceController');
    Route::resource('orders', 'OrdersController');
    Route::resource('loyalty_rewords', 'LoyaltyrewordsController');
    Route::resource('corporate_subscriptions', 'CorporatesubscriptionsController');

    Route::prefix('dashboard')->group(function () {
        Route::get('/sms-groups', 'BulksendController@index');
        Route::post('/send-text', 'BulksendController@sendMessage');
        Route::get('/single-sms', 'BulksendController@singleUser');


    });

    //cooporate groups
    Route::prefix('corporate_subscription')->group(function () {
        Route::resource('groups', 'CorporatesubscriptiongroupsController');
        Route::post('temp/users', 'CorporatesubscriptiongroupsController@importusers');
        Route::resource('meals', 'CorporatesubscriptionsmealsController');
        Route::resource('subscribers', 'CorporatesubscriptionusersController');
        Route::resource('grubsubsorders', 'CorporateordersController');
        Route::resource('payments', 'CorporatepaymentController');

    });


    //Mpesa transactions
     Route::prefix('mpesa')->group(function () {
        Route::resource('payments', 'MpesaPaymentsController');
    });


    ///livewire routes
    //Route::view('allstores','store.index');


});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/corporatesubscriptionmeals/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h5>Add Meal</h5>
        </div>
    </div>
      <div class="row">
        <div class="col-6">
            @if(Session::has('message'))
                <p class="alert alert-success">{{ Session::get('message') }}</p>
            @endif
            <div class="clearfix"></div>
         <form action="{{ route('meals.store') }}" method="POST"  enctype="multipart/form-data">
             @csrf
               <div class="form-group">
                    <select name="subscriptions_id" class="form-control" name="" required>
                       <option> Choose Subscription </option>
                        @foreach ($subscriptions as $sub)
                          <option  value="{{ $sub->id }}">{{ $sub->subscriptions_name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="instock">In Stock</label>
                    <label  class="switch">
                        <input id="instock" type="checkbox">
                        <span class="slider round"></span>
                    </label>
                </div>
                <div class="form-group">
                 <input type="text"  class="form-control" value="{{ old('meal_name') }}" name='meal_name' class="form-control" id="" placeholder="Meal Name">
                  @if ($errors->has('meal_name')) <div class="alert alert-danger">{{ $errors->first('meal_name') }} </div> @endif
                </div>
                <div class="form-group">
                    <textarea class="form-control rounded-0"  name='description'  value="{{ old('description') }}"  placeholder="Description"  rows="3"></textarea>
                    @if ($errors->has('description')) <div class="alert alert-danger">{{ $errors->first('description') }} </div> @endif
                </div>
                <div class="form-group">
                    <div class="custom-file">
                        <input type="file" name="meal_image_ur" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose Image</label>
                    </div>
                     @if ($errors->has('meal_image_ur')) <div class="alert alert-danger">{{ $errors->first('meal_image_ur') }} </div> @endif
                </div>
                <div class="form-group">
                    <input id="pac-input" class="form-control" name="price" type="text" placeholder="price">
                     @if ($errors->has('price')) <div class="alert alert-danger">{{ $errors->first('price') }} </div> @endif
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
           </form>

        </div>
       </div>
    </div>
@endsection

<script>
  $(function() {
    $('#instock').prop('YES', true);
  })
</script>

resources/views/corporatesubscriptionmeals/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h5>Corporate Meals</h5>
        </div>
        <div class="col-6 text-right">
            <a href="{{ route('meals.create') }}" class="btn btn-primary">Add Meal</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Subscriptions Type</th>
                            <th>Meal</th>
                            <th>Description</th>
                            <th>In Stock</th>
                            <th>Price</th>
                            <th>Created at</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php ($i = 0)
                          @foreach ($meals as $meal)
                            <tr>
                                <td>{{ ++$i }}</td>
                                 <td>{{ $meal['corporatesubscriptions']['subscriptions_name']}}</td>
                                <td>{{ $meal['meal_name']}}</td>
                                <td>{{ $meal['description']}}</td>
                                <td>{{ $meal['inStock'] }}</td>
                                <td>{{ $meal['price'] }}</td>
                                <td>{{ $meal['created_at'] }}</td>
                                {{--  <td><a href="{{  route('meals.show', ['subscription_id' => $meal['corporatesubscriptions']['id']]) }}">View Members</a></td>  --}}
                            </tr>
                            @endforeach
                    </tbody>
                </table>
           </div>
      </div>
</div>
@endsection

resources/views/corporatesubscriptionmeals/show.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h4>Cooporate Groups</h4>
        </div>
        <div class="col-6 text-right">
            <a href="{{ route('groups.create') }}" class="btn btn-primary">Add Group</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Group Name</th>
                            <th>Contact Person</th>
                            <th>Phonenumber</th>
                            <th>Total Members</th>
                            <th>Created at</th>
                            <th>View Members </th>
                        </tr>
                    </thead>
                    <tbody>

                        @php ($i = 0)
                          @foreach ($groups as $group)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td><a href="{{  route('groups.show', $group['id']) }}">{{ $group['name'] }}</a></td>
                                <td>{{ $group['phoneNumber'] }}</td>
                                <td>{{ $group['contact_person'] }}</td>
                                <td>{{ $group['phoneNumber'] }}</td>
                                <td>{{ $group['membersNo'] }}</td>
                                <td>{{ $group['created_at'] }}</td>
                                <td><a href="{{  route('groups.show', $group['id']) }}">View Members</a></td>

                            </tr>
                            @endforeach
                            
                    </tbody>
                </table>
           </div>
      </div>
</div>
@endsection