routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


//public mpesa webhooks
Route::post('/webhook', 'PaymentController@webhook');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    //only logged in users allowed below
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    //only logged inn user allowed above

    Route::get('/', 'HomeController@index');

    Route::resource('users', 'UsersController');
    Route::resource('store', 'StoreController');
    Route::resource('customers', 'CustomersController');
    Route::resource('itemcategories', 'StoreCategoryController');
    Route::resource('itemtype', 'ItemtypeController');
    Route::resource('items', 'ItemsController');
    Route::resource('drivers', 'DriversController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('delivery_services', 'DeliveryServiceController');
    Route::resource('orders', 'OrdersController');
    Route::resource('loyalty_rewords', 'LoyaltyrewordsController');
    Route::resource('corporate_subscriptions', 'CorporatesubscriptionsController');

    Route::prefix('dashboard')->group(function () {
        Route::get('/sms-groups', 'BulksendController@index');
        Route::post('/send-text', 'BulksendController@sendMessage');
        Route::get('/single-sms', 'BulksendController@singleUser');


    });

    //cooporate groups
    Route::prefix('corporate_subscription')->group(function () {
        Route::resource('groups', 'CorporatesubscriptiongroupsController');
        Route::post('temp/users', 'CorporatesubscriptiongroupsController@importusers');
        Route::resource('meals', 'CorporatesubscriptionsmealsController');
        Route::resource('subscribers', 'CorporatesubscriptionusersController');
        Route::resource('grubsubsorders', 'CorporateordersController');
        Route::resource('payments', 'CorporatepaymentController');

    });


    //Mpesa transactions
     Route::prefix('mpesa')->group(function () {
        Route::resource('payments', 'MpesaPaymentsController');
    });


    ///livewire routes
    //Route::view('allstores','store.index');


});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/itemcats/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h4>Add Category</h4>
        </div>
    </div>
      <div class="row">
        <div class="col-6">
         <form action="{{ route('itemcategories.store') }}" method="POST">
             @csrf
                <div class="form-group">
                    <label for="">Service Type</label>
                    <select class="form-control form-control-lg">
                        @foreach ($services as $service)
                          <option>{{ $service["vServiceName_EN"] }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                        <label for="">Store Name</label>
                        <select class="form-control form-control-lg">
                                @foreach ($services as $service)
                                  <option>{{ $service["vServiceName_EN"] }}</option>
                              @endforeach
                        </select>
                    </div>
                <div class="form-group">
                    <label for="">Category Name</label>
                 <input type="text"  class="form-control" value="{{ old('category_name') }}" name='category_name' class="form-control" id="" placeholder="Category Name" >
                </div>
                <div class="form-group">
                    <label for="">Store Name</label>
                    <select class="form-control form-control-lg">
                            @foreach ($orderNo as $order)
                                <option>{{ $order["iDisplayOrder"] }}</option>
                            @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
           </form>

        </div>
       </div>
    </div>


@endsection

resources/views/itemcats/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h3>Item Categories</h3>
        </div>
        <div class="col-6 text-right">
            <a href="{{ route('itemcategories.create') }}" class="btn btn-primary">Add Category</a>
        </div>
        <div class="col-12">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <td>{{ '#' }}</td>
                            <th>Cat Name </th>
                            <th>Store </th>
                            <th>Display Order</th>
                            <td>Items</td>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                          @php ($i = 1)
                          @foreach ($itemcats as $item)
                            <tr>
                               <td> {{ ++$i }}</td>
                                <td>{{ $item['vMenu_EN'] }}</td>
                                @foreach ($item['store'] as $storeName)
                                   <td>{{ $storeName['vCompany'] }}</td>
                                @endforeach
                                <td>{{ $item['iDisplayOrder'] }}</td>
                                <td> </td>
                                <td>{{ $item['eStatus'] == "Active" ? 'Active' : ''}} {{ $item['eStatus'] == "Deleted" ? 'Deleted' : ''}}</td>
                                <td>
                                <td>
                                    <a  href="" title="view this service" class="btn btn-default btn-sm ">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a  href="{{ route('itemcategories.edit', $item['iFoodMenuId'])}}" title="edit this service" class="btn btn-default btn-sm ">
                                            <i class="fas fa-edit"></i>
                                    </a>
</td>
                            </tr>
                            @endforeach
                    </tbody>
                </table>
        </div>
    </div>
@endsection