routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


//public mpesa webhooks
Route::post('/webhook', 'PaymentController@webhook');

Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    //only logged in users allowed below
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
    //only logged inn user allowed above

    Route::get('/', 'HomeController@index');

    Route::resource('users', 'UsersController');
    Route::resource('store', 'StoreController');
    Route::resource('customers', 'CustomersController');
    Route::resource('itemcategories', 'StoreCategoryController');
    Route::resource('itemtype', 'ItemtypeController');
    Route::resource('items', 'ItemsController');
    Route::resource('drivers', 'DriversController');
    Route::resource('vehicles', 'VehiclesController');
    Route::resource('delivery_services', 'DeliveryServiceController');
    Route::resource('orders', 'OrdersController');
    Route::resource('loyalty_rewords', 'LoyaltyrewordsController');
    Route::resource('corporate_subscriptions', 'CorporatesubscriptionsController');

    Route::prefix('dashboard')->group(function () {
        Route::get('/sms-groups', 'BulksendController@index');
        Route::post('/send-text', 'BulksendController@sendMessage');
        Route::get('/single-sms', 'BulksendController@singleUser');


    });

    //cooporate groups
    Route::prefix('corporate_subscription')->group(function () {
        Route::resource('groups', 'CorporatesubscriptiongroupsController');
        Route::post('temp/users', 'CorporatesubscriptiongroupsController@importusers');
        Route::resource('meals', 'CorporatesubscriptionsmealsController');
        Route::resource('subscribers', 'CorporatesubscriptionusersController');
        Route::resource('grubsubsorders', 'CorporateordersController');
        Route::resource('payments', 'CorporatepaymentController');

    });


    //Mpesa transactions
     Route::prefix('mpesa')->group(function () {
        Route::resource('payments', 'MpesaPaymentsController');
    });


    ///livewire routes
    //Route::view('allstores','store.index');


});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Deliveryservice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Deliveryservice extends Model
{
    protected $table        = 'service_categories';
    protected $primaryKey   = 'iServiceId';
    public $incrementing    = false;
    public    $timestamps   = false;
    protected $guarded      = ['iServiceId'];

}

app/Http/Controllers/DeliveryServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Deliveryservice;

class DeliveryServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $services = Deliveryservice::all();
        //dd($services);
        return view('/deliveryservices/index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('/deliveryservices/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'service_image' => 'required|image|mimes:jpeg,png,gif,svg|max:2048'
        ]);

        //check and get file name and form parth
        if($request->hasfile('service_image'))
         {
            $getfile      =  $validation['service_image'];
            $image_name   = str_replace(' ', '', $getfile); // remove space from string
            $filename     = strtolower($image_name . time() . '.' . $getfile->getClientOriginalExtension());
            $imagepathurl = $getfile->storeAs('photos', $filename);
         }

        Deliveryservice::create([
            'vService'      => request('service_name'),
            'iDisplayOrder' => request('display_order'),
            'vImage'        => $filename
        ]);

        return redirect('delivery_services')->with('success', 'Service Delivery added Seccesfully');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Deliveryservice::find($id);
        return view('/deliveryservices/edit',compact('service','id'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $service = Deliveryservice::find($id);
        $validation = $request->validate([
            'service_image' => 'required|file|image|mimes:jpeg,png,gif,webp|max:2048',
            'service_image' => 'required',
            'display_order' => 'required'

        ]);

        //check and get file name and form parth
        if($request->hasfile('service_image'))
         {
            $getfile      =  $validation['service_image'];
            $image_name   = str_replace(' ', '', $request->input('service_name')); // remove space from string
            $filename     = $image_name . time() . '.' . $getfile->getClientOriginalExtension();
            $imagepathurl = $getfile->storeAs('photos', $filename);
         }
         $service->vService = request('service_name');
         $service->iDisplayOrder = request('display_order');
         $service->vImage = $imagepathurl;

         //dd($service);
         $service->update();

        return redirect('delivery_services')->with('success', 'Service Delivery updated Seccesfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Deliveryservice::find($id);
         $service->delete();
         return redirect('delivery_services')->with('success', 'Service Delivery Deleted Seccesfully');
    }
}

resources/views/deliveryservices/create.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-8">
            <h4>Add Service</h4>
        </div>
    </div>
      <div class="row">
        <div class="col-6">
         <form action="{{ route('delivery_services.store') }}" method="POST" enctype="multipart/form-data">
             @csrf
                <div class="form-group">
                    <label for="">Service Name</label>
                 <input type="text"  class="form-control" value="{{ old('service_name') }}" name='service_name' class="form-control" id="" placeholder="Store Name" >
                </div>
                <div class="form-group">
                    <label for="display_order">Display Order</label>
                    <select value="{{ old('display_order') }}" name="display_order" class="form-control form-control-lg">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="store_logo">Service Image</label>
                    <div class="custom-file">
                            <input type="file" name="service_image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose Image</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
           </form>
        </div>
       </div>
    </div>
@endsection

resources/views/deliveryservices/edit.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-6">
            <h4>Update Delivery Service</h4>
        </div>
        <div class="col-6 text-right">
                <a href="{{ route('delivery_services.index') }}" class="btn  bg-warning ">All Delivery Services</a>
        </div>
    </div>
      <div class="row">
        <div class="col-6">
         <form action="{{ route('delivery_services.update', $service->iServiceId) }}" method="POST" enctype="multipart/form-data">
            @method('PATCH')
            @csrf
                <div class="form-group">
                    <label for="">Service Name</label>
                 <input type="text"  class="form-control" value="{{ $service->vService }}" name='service_name' class="form-control" id="" placeholder="Store Name" >
                </div>
                <div class="form-group">
                    <label for="display_order">Display Order</label>
                    <select value="{{ old('display_order') }}" name="display_order" class="form-control form-control-lg">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                    </select>
                </div>

                <div class="form-group">
                    <label for="store_logo">Service Image</label>
                    <div class="custom-file">
                            <input type="file" name="service_image" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose Image</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
           </form>
        </div>
       </div>
    </div>
@endsection

resources/views/deliveryservices/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="row">
        <div class="col-lg-8">
          <h5> Services Types</h5>
           </div>
          <div class="col-lg-4">
          <a  href="{{ route('delivery_services.create') }}" class="btn bg-warning ">Add Service Type</a>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @if (\Session::has('success'))
            <div class="alert alert-success">
                <p>{{ \Session::get('success') }}</p>
            </div><br />
            @endif
        </div>
        <div class="col-12">
                <table class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Service Type</th>
                            <th>Image</th>
                            <th>Display Order</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                    @php ($count = 1)
                          @foreach ($services as $service)
                            <tr>
                                <td>{{ $count++ }}</td>
                                <td>{{ $service->vService }}</td>
                                <td>
                                <img src="{{ asset('storage/photo/'.$service->vImage) }}"/>
                                </td>
                                <td>{{ $service->iDisplayOrder }}</td>
                                <td>
                                  <span  class="bg-success p-2 rounded-pill text-white">{{ $service['eStatus'] }} </span>
                                </td>
                                <td>
                                    <a  href="" title="view this service" class="btn btn-default btn-sm ">
                                        <i class="fas fa-eye"></i>
                                    </a>
                                    <a  href="{{ route('delivery_services.edit', $service->iServiceId)}}" title="edit this service" class="btn btn-default btn-sm ">
                                            <i class="fas fa-edit"></i>
                                    </a>

                                    <form action="{{ route('delivery_services.destroy',$service->iServiceId) }}" method="POST" enctype="multipart/form-data">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-default btn-sm"> <i class="far fa-trash-alt"></i></button>
                                    </form>
                                </td>

                            </tr>
                            @endforeach
                    </tbody>
                </table>
           </div>
      </div>
</div>
@endsection